const conceptFieldPairs = [
  ["Astrobiology", "Fermi Paradox"],
  ["Astrobiology", "Extremophiles"],
  ["Astrobiology", "Exoplanet Atmospheres"],
  ["Astrobiology", "Astrobiochemistry"],
  ["Astrobiology", "Panspermia Hypothesis"],
  ["Astrobiology", "Drake Equation"],
  ["Astrobiology", "Habitability Zone"],
  ["Astrobiology", "Biomarkers"],
  ["Astrobiology", "Exoplanet Habitability"],
  ["Astrobiology", "Exobiology"],
  ["Quantum Physics", "Quantum Entanglement"],
  ["Quantum Physics", "Heisenberg Uncertainty Principle"],
  ["Quantum Physics", "Wave-Particle Duality"],
  ["Quantum Physics", "Quantum Tunneling"],
  ["Quantum Physics", "Schrodinger's Cat"],
  ["Quantum Physics", "Quantum Decoherence"],
  ["Quantum Physics", "Quantum Zeno Effect"],
  ["Quantum Physics", "Bell's Theorem"],
  ["Quantum Physics", "Quantum Superposition"],
  ["Quantum Physics", "Quantum Chaos"],
  ["Neuroscience", "Neuroplasticity"],
  ["Neuroscience", "Mirror Neurons"],
  ["Neuroscience", "Brain-Computer Interface"],
  ["Neuroscience", "Synaptic Pruning"],
  ["Neuroscience", "Neurogenesis"],
  ["Neuroscience", "Neural Oscillations"],
  ["Neuroscience", "Brain Mapping"],
  ["Neuroscience", "Neuroethics"],
  ["Neuroscience", "Default Mode Network"],
  ["Ethnobotany", "Psychoactive Plants"],
  ["Ethnobotany", "Traditional Herbal Medicine"],
  ["Ethnobotany", "Plant Domestication"],
  ["Ethnobotany", "Ethnopharmacology"],
  ["Ethnobotany", "Medicinal Plants"],
  ["Ethnobotany", "Agricultural Biodiversity"],
  ["Ethnobotany", "Ethnobotanical Gardens"],
  ["Ethnobotany", "Traditional Ecological Knowledge"],
  ["Ethnobotany", "Ethnobotanical Keystone Species"],
  ["Cultural Anthropology", "Rites of Passage"],
  ["Cultural Anthropology", "Kinship Systems"],
  ["Cultural Anthropology", "Cultural Relativism"],
  ["Cultural Anthropology", "Symbolic Anthropology"],
  ["Cultural Anthropology", "Ethnographic Method"],
  ["Cultural Anthropology", "Cultural Evolution"],
  ["Cultural Anthropology", "Material Culture"],
  ["Cultural Anthropology", "Culture and Personality"],
  ["Cultural Anthropology", "Fictive Kinship"],
  ["Cultural Anthropology", "Cargo Cults"],
  ["Paleontology", "Fossilization Processes"],
  ["Paleontology", "Dinosaur Extinction"],
  ["Paleontology", "Paleobiology"],
  ["Paleontology", "Taphonomy"],
  ["Paleontology", "Mass Extinctions"],
  ["Paleontology", "Trace Fossils"],
  ["Paleontology", "Evolutionary Paleoecology"],
  ["Paleontology", "Paleoclimatology"],
  ["Paleontology", "Lazarus Taxa"],
  ["Oceanography", "Marine Biogeochemistry"],
  ["Oceanography", "Thermohaline Circulation"],
  ["Oceanography", "Ocean Acidification"],
  ["Oceanography", "Marine Ecosystems"],
  ["Oceanography", "Marine Geophysics"],
  ["Oceanography", "Biological Oceanography"],
  ["Oceanography", "Chemical Oceanography"],
  ["Oceanography", "Physical Oceanography"],
  ["Oceanography", "Ekman Transport"],
  ["Oceanography", "Langmuir Circulation"],
  ["Cognitive Science", "Theory of Mind"],
  ["Cognitive Science", "Embodied Cognition"],
  ["Cognitive Science", "Artificial Neural Networks"],
  ["Cognitive Science", "Cognitive Dissonance"],
  ["Cognitive Science", "Cognitive Neuroscience"],
  ["Cognitive Science", "Attention Mechanisms"],
  ["Cognitive Science", "Memory Systems"],
  ["Cognitive Science", "Cognitive Development"],
  ["Cognitive Science", "Blindsight"],
  ["Cryptozoology", "Bigfoot Phenomenon"],
  ["Cryptozoology", "Loch Ness Monster"],
  ["Cryptozoology", "Chupacabra"],
  ["Cryptozoology", "Mokele-mbembe"],
  ["Cryptozoology", "Yeti Legends"],
  ["Cryptozoology", "Mothman"],
  ["Cryptozoology", "Jersey Devil"],
  ["Cryptozoology", "Thunderbird"],
  ["Cryptozoology", "Cryptid Hybridization"],
  ["Aerospace Engineering", "Spacecraft Propulsion"],
  ["Aerospace Engineering", "Aeroelasticity"],
  ["Aerospace Engineering", "Hypersonic Flight"],
  ["Aerospace Engineering", "Orbital Mechanics"],
  ["Aerospace Engineering", "Space Elevator"],
  ["Aerospace Engineering", "Aerodynamics"],
  ["Aerospace Engineering", "Satellite Communication"],
  ["Aerospace Engineering", "Space Habitats"],
  ["Aerospace Engineering", "Scramjet Propulsion"],
  ["Aerospace Engineering", "Aerocapture"],
  ["Forensic Science", "DNA Fingerprinting"],
  ["Forensic Science", "Ballistic Analysis"],
  ["Forensic Science", "Forensic Toxicology"],
  ["Forensic Science", "Digital Forensics"],
  ["Forensic Science", "Forensic Anthropology"],
  ["Forensic Science", "Forensic Odontology"],
  ["Forensic Science", "Bloodstain Pattern Analysis"],
  ["Forensic Science", "Crime Scene Investigation"],
  ["Forensic Science", "Forensic Entomology"],
  ["Forensic Science", "Forensic Palynology"],
  ["Forensic Science", "Forensic Taphonomy"],
  ["Mycology", "Fungal Symbiosis"],
  ["Mycology", "Mycorrhizal Networks"],
  ["Mycology", "Fungal Pathogenesis"],
  ["Mycology", "Mushroom Cultivation"],
  ["Mycology", "Fungal Biotechnology"],
  ["Mycology", "Mycotoxins"],
  ["Mycology", "Fungal Ecology"],
  ["Mycology", "Lichenology"],
  ["Mycology", "Mycelial Networks"],
  ["Astrophysics", "Black Hole Thermodynamics"],
  ["Astrophysics", "Cosmic Inflation"],
  ["Astrophysics", "Dark Matter"],
  ["Astrophysics", "Gravitational Waves"],
  ["Astrophysics", "Neutron Stars"],
  ["Astrophysics", "Pulsars"],
  ["Astrophysics", "Galactic Formation"],
  ["Astrophysics", "Cosmic Microwave Background"],
  ["Astrophysics", "Dark Energy"],
  ["Geology", "Plate Tectonics"],
  ["Geology", "Volcanic Activity"],
  ["Geology", "Mineral Formation"],
  ["Geology", "Seismic Hazards"],
  ["Geology", "Sedimentology"],
  ["Geology", "Geomorphology"],
  ["Geology", "Petrology"],
  ["Geology", "Geochronology"],
  ["Geology", "Isostatic Rebound"],
  ["Geology", "Mantle Convection"],
  ["Sociolinguistics", "Language and Identity"],
  ["Sociolinguistics", "Dialectology"],
  ["Sociolinguistics", "Language Contact"],
  ["Sociolinguistics", "Code-Switching"],
  ["Sociolinguistics", "Language Ideologies"],
  ["Sociolinguistics", "Language Policy"],
  ["Sociolinguistics", "Language and Gender"],
  ["Sociolinguistics", "Language Revitalization"],
  ["Sociolinguistics", "Diglossia"],
  ["Sociolinguistics", "Linguistic Landscape"],
  ["Bioinformatics", "Genome Sequencing"],
  ["Bioinformatics", "Protein Structure Prediction"],
  ["Bioinformatics", "Computational Genomics"],
  ["Bioinformatics", "Phylogenetics"],
  ["Bioinformatics", "Metagenomics"],
  ["Bioinformatics", "Genomic Data Integration"],
  ["Bioinformatics", "Transcriptomics"],
  ["Bioinformatics", "Proteomics"],
  ["Bioinformatics", "Genome Assembly"],
  ["Bioinformatics", "Protein-Protein Interaction"],
  ["Nanotechnology", "Nanomaterials"],
  ["Nanotechnology", "Nanomedicine"],
  ["Nanotechnology", "Nanoelectronics"],
  ["Nanotechnology", "Molecular Nanotechnology"],
  ["Nanotechnology", "Nanofabrication"],
  ["Nanotechnology", "Nanotoxicology"],
  ["Nanotechnology", "Nanophotonics"],
  ["Nanotechnology", "Nanomechanics"],
  ["Nanotechnology", "Quantum Dots"],
  ["Environmental Science", "Climate Change"],
  ["Environmental Science", "Biodiversity Conservation"],
  ["Environmental Science", "Sustainable Development"],
  ["Environmental Science", "Pollution Mitigation"],
  ["Environmental Science", "Ecosystem Services"],
  ["Environmental Science", "Environmental Monitoring"],
  ["Environmental Science", "Pollutant Transport"],
  ["Environmental Science", "Ecological Restoration"],
  ["Environmental Science", "Bioaccumulation"],
  ["Environmental Science", "Biomagnification"],
  ["Environmental Science", "Eutrophication"],
  ["Environmental Science", "Biomimicry"],
  ["Environmental Science", "Biomimetic Design"],
  ["Environmental Science", "Biospeleology"],
  ["Archaeology", "Artifact Analysis"],
  ["Archaeology", "Archaeological Dating"],
  ["Archaeology", "Cultural Heritage"],
  ["Archaeology", "Paleoanthropology"],
  ["Archaeology", "Underwater Archaeology"],
  ["Archaeology", "Archaeometry"],
  ["Archaeology", "Experimental Archaeology"],
  ["Archaeology", "Historical Archaeology"],
  ["Archaeology", "Lidar Mapping"],
  ["Archaeology", "Ground-Penetrating Radar"],
  ["Archaeology", "Dendrochronology"],
  ["Meteorology", "Atmospheric Dynamics"],
  ["Meteorology", "Weather Prediction"],
  ["Meteorology", "Tropical Cyclones"],
  ["Meteorology", "Climate Modeling"],
  ["Meteorology", "Severe Weather"],
  ["Meteorology", "Atmospheric Pressure"],
  ["Meteorology", "Weather Radar"],
  ["Meteorology", "Climatology"],
  ["Meteorology", "Mesoscale Convective Systems"],
  ["Meteorology", "Atmospheric Rivers"],
  ["Meteorology", "Polar Vortex"],
  ["Genetics", "Gene Editing"],
  ["Genetics", "Epigenetics"],
  ["Genetics", "Genetic Disorders"],
  ["Genetics", "Population Genetics"],
  ["Genetics", "Genomic Imprinting"],
  ["Genetics", "Genomic Instability"],
  ["Genetics", "Gene Therapy"],
  ["Genetics", "Genetic Counseling"],
  ["Genetics", "Transposons"],
  ["Genetics", "CRISPR Gene Editing"],
  ["Evolutionary Biology", "Natural Selection"],
  ["Evolutionary Biology", "Speciation"],
  ["Evolutionary Biology", "Adaptive Radiation"],
  ["Evolutionary Biology", "Molecular Evolution"],
  ["Evolutionary Biology", "Sexual Selection"],
  ["Evolutionary Biology", "Mimicry"],
  ["Evolutionary Biology", "Co-evolution"],
  ["Evolutionary Biology", "Phylogeography"],
  ["Evolutionary Biology", "Punctuated Equilibrium"],
  ["Cybersecurity", "Cryptographic Protocols"],
  ["Cybersecurity", "Network Security"],
  ["Cybersecurity", "Malware Analysis"],
  ["Cybersecurity", "Cyber-Physical Systems"],
  ["Cybersecurity", "Cyber Espionage"],
  ["Cybersecurity", "Information Assurance"],
  ["Cybersecurity", "Cyber Threat Intelligence"],
  ["Cybersecurity", "Cyber Warfare"],
  ["Cybersecurity", "Zero-day Exploit"],
  ["Cybersecurity", "Advanced Persistent Threat"],
  ["Artificial Intelligence", "Machine Learning"],
  ["Artificial Intelligence", "Natural Language Processing"],
  ["Artificial Intelligence", "Computer Vision"],
  ["Artificial Intelligence", "Reinforcement Learning"],
  ["Artificial Intelligence", "Deep Learning"],
  ["Artificial Intelligence", "Explainable AI"],
  ["Artificial Intelligence", "Generative Adversarial Networks"],
  ["Artificial Intelligence", "Robust AI"],
  ["Artificial Intelligence", "Quantum Machine Learning"],
  ["Artificial Intelligence", "Quantum Supremacy"],
  ["Linguistics", "Phonetics"],
  ["Linguistics", "Syntax"],
  ["Linguistics", "Semantics"],
  ["Linguistics", "Pragmatics"],
  ["Linguistics", "Morphology"],
  ["Linguistics", "Phonology"],
  ["Linguistics", "Sociophonetics"],
  ["Linguistics", "Typology"],
  ["Linguistics", "Garden Path Sentences"],
  ["Linguistics", "Syntactic Ambiguity"],
  ["Robotics", "Robot Kinematics"],
  ["Robotics", "Autonomous Systems"],
  ["Robotics", "Humanoid Robots"],
  ["Robotics", "Swarm Robotics"],
  ["Robotics", "Industrial Robots"],
  ["Robotics", "Service Robots"],
  ["Robotics", "Medical Robotics"],
  ["Robotics", "Robotic Perception"],
  ["Robotics", "Soft Robotics"],
  ["Robotics", "Biomimetic Robotics"],
  ["Space Medicine", "Microgravity Effects"],
  ["Space Medicine", "Radiation Exposure"],
  ["Space Medicine", "Space Nutrition"],
  ["Space Medicine", "Psychological Challenges"],
  ["Space Medicine", "Telemedicine in Space"],
  ["Space Medicine", "Space Adaptation Syndrome"],
  ["Space Medicine", "Bone Density Loss"],
  ["Space Medicine", "Cardiovascular Changes"],
  ["Space Medicine", "Microgravity Osteoporosis"],
  ["Space Medicine", "Space Motion Sickness"],
  ["Urban Planning", "Smart Cities"],
  ["Urban Planning", "Sustainable Urban Design"],
  ["Urban Planning", "Urban Sprawl"],
  ["Urban Planning", "Transit-Oriented Development"],
  ["Urban Planning", "Public Space Design"],
  ["Urban Planning", "Urban Agriculture"],
  ["Urban Planning", "Urban Resilience"],
  ["Urban Planning", "Land Use Planning"],
  ["Urban Planning", "New Urbanism"],
  ["Demography", "Population Growth"],
  ["Demography", "Migration Patterns"],
  ["Demography", "Aging Populations"],
  ["Demography", "Fertility Rates"],
  ["Demography", "Population Projections"],
  ["Demography", "Mortality Rates"],
  ["Demography", "Demographic Transition"],
  ["Demography", "Life Expectancy"],
  ["Demography", "Dependency Ratio"],
  ["Demography", "Demographic Dividend"],
  ["Climatology", "Paleoclimatology"],
  ["Climatology", "Climate Feedbacks"],
  ["Climatology", "Anthropogenic Climate Change"],
  ["Climatology", "Atmospheric Chemistry"],
  ["Climatology", "Ice Core Analysis"],
  ["Climatology", "Paleotempestology"],
  ["Climatology", "Atmospheric Circulation"],
  ["Climatology", "Climate Sensitivity"],
  ["Climatology", "Albedo Effect"],
  ["Climatology", "Urban Heat Island"],
  ["Biophysics", "Molecular Motors"],
  ["Biophysics", "Membrane Biophysics"],
  ["Biophysics", "Biophysical Techniques"],
  ["Biophysics", "Single-Molecule Biophysics"],
  ["Biophysics", "DNA Mechanics"],
  ["Biophysics", "Protein Folding"],
  ["Biophysics", "Cell Biophysics"],
  ["Biophysics", "Biophotonics"],
  ["Biophysics", "Allosteric Regulation"],
  ["Biophysics", "Molecular Docking"],
  ["Epidemiology", "Disease Outbreaks"],
  ["Epidemiology", "Vaccine Efficacy"],
  ["Epidemiology", "Epidemiological Modeling"],
  ["Epidemiology", "Public Health Interventions"],
  ["Epidemiology", "Chronic Disease Epidemiology"],
  ["Epidemiology", "Infectious Disease Modeling"],
  ["Epidemiology", "Nutritional Epidemiology"],
  ["Epidemiology", "Epidemiologic Surveillance"],
  ["Epidemiology", "R0 Number"],
  ["Epidemiology", "Vector-borne Disease"],
  ["Epidemiology", "Superspreader Events"],
  ["Human Geography", "Urbanization"],
  ["Human Geography", "Cultural Landscapes"],
  ["Human Geography", "Geopolitics"],
  ["Human Geography", "Spatial Analysis"],
  ["Human Geography", "Cultural Geography"],
  ["Human Geography", "Economic Geography"],
  ["Human Geography", "Political Geography"],
  ["Human Geography", "Health Geography"],
  ["Human Geography", "Psychogeography"],
  ["Human Geography", "Time Geography"],
  ["Zoology", "Animal Behavior"],
  ["Zoology", "Comparative Anatomy"],
  ["Zoology", "Endangered Species"],
  ["Zoology", "Ethology"],
  ["Zoology", "Marine Mammals"],
  ["Zoology", "Primatology"],
  ["Zoology", "Herpetology"],
  ["Zoology", "Ornithology"],
  ["Zoology", "Eusociality"],
  ["Zoology", "Kin Selection"],
  ["Zoology", "Altruism in Animals"],
  ["Marine Biology", "Coral Reef Ecology"],
  ["Marine Biology", "Marine Mammalogy"],
  ["Marine Biology", "Plankton Ecology"],
  ["Marine Biology", "Deep-Sea Biology"],
  ["Marine Biology", "Marine Invertebrates"],
  ["Marine Biology", "Marine Microbiology"],
  ["Marine Biology", "Marine Biotechnology"],
  ["Marine Biology", "Marine Conservation"],
  ["Marine Biology", "Hydrothermal Vents"],
  ["Marine Biology", "Coral Bleaching"],
  ["Ecotoxicology", "Bioaccumulation"],
  ["Ecotoxicology", "Environmental Monitoring"],
  ["Ecotoxicology", "Toxicity Testing"],
  ["Ecotoxicology", "Chemical Pollution"],
  ["Ecotoxicology", "Ecological Risk Assessment"],
  ["Ecotoxicology", "Environmental Toxicology"],
  ["Ecotoxicology", "Toxicokinetics"],
  ["Ecotoxicology", "Aquatic Toxicology"],
  ["Ecotoxicology", "Bioamplification"],
  ["Ecotoxicology", "Endocrine Disruption"],
  ["Ecotoxicology", "Biomarkers"],
  ["Planetary Science", "Planetary Atmospheres"],
  ["Planetary Science", "Surface Geology"],
  ["Planetary Science", "Planetary Magnetism"],
  ["Planetary Science", "Exoplanet Detection"],
  ["Planetary Science", "Planetary Geology"],
  ["Planetary Science", "Planetary Rings"],
  ["Planetary Science", "Planetary Interiors"],
  ["Planetary Science", "Planetary Magnetosphere"],
  ["Planetary Science", "Goldilocks Zone"],
  ["Planetary Science", "Exoplanetology"],
  ["Planetary Science", "Exometeorology"],
  ["Computational Biology", "Systems Biology"],
  ["Computational Biology", "Biological Networks"],
  ["Computational Biology", "Computational Drug Discovery"],
  ["Computational Biology", "Synthetic Biology"],
  ["Computational Biology", "Bioinformatics Algorithms"],
  ["Computational Biology", "Computational Genomics"],
  ["Computational Biology", "Computational Proteomics"],
  ["Computational Biology", "Biological Data Mining"],
  ["Computational Biology", "Phylogenetic Trees"],
  ["Computational Biology", "Protein Homology Modeling"],
  ["Computational Biology", "Molecular Dynamics Simulation"],
  ["Environmental Psychology", "Place Attachment"],
  ["Environmental Psychology", "Restorative Environments"],
  ["Environmental Psychology", "Environmental Stress"],
  ["Environmental Psychology", "Sustainable Behavior"],
  ["Environmental Psychology", "Environmental Cognition"],
  ["Environmental Psychology", "Place Identity"],
  ["Environmental Psychology", "Pro-environmental Behavior"],
  ["Environmental Psychology", "Environmental Perception"],
  ["Environmental Psychology", "Attention Restoration Theory"],
  ["Social Psychology", "Group Dynamics"],
  ["Social Psychology", "Social Influence"],
  ["Social Psychology", "Interpersonal Attraction"],
  ["Social Psychology", "Prejudice and Discrimination"],
  ["Social Psychology", "Social Identity Theory"],
  ["Social Psychology", "Attribution Theory"],
  ["Social Psychology", "Self-Perception Theory"],
  ["Social Psychology", "Social Comparison Theory"],
  ["Social Psychology", "Fundamental Attribution Error"],
  ["Social Psychology", "Groupthink"],
  ["Conservation Biology", "Habitat Fragmentation"],
  ["Conservation Biology", "Invasive Species"],
  ["Conservation Biology", "Conservation Genetics"],
  ["Conservation Biology", "Protected Areas"],
  ["Conservation Biology", "Biodiversity Hotspots"],
  ["Conservation Biology", "Conservation Prioritization"],
  ["Conservation Biology", "Community Conservation"],
  ["Conservation Biology", "Conservation Policy"],
  ["Conservation Biology", "Keystone Species"],
  ["Conservation Biology", "Umbrella Species"],
  ["Astrobiochemistry", "Chemical Evolution"],
  ["Astrobiochemistry", "Prebiotic Chemistry"],
  ["Astrobiochemistry", "Molecular Biosignatures"],
  ["Astrobiochemistry", "Extremophile Metabolism"],
  ["Astrobiochemistry", "Organic Molecules in Space"],
  ["Astrobiochemistry", "Extraterrestrial Life Detection"],
  ["Astrobiochemistry", "Planetary Protection"],
  ["Astrobiochemistry", "Astrobiological Missions"],
  ["Astrobiochemistry", "Panspermia Hypothesis"],
  ["Astrobiochemistry", "Extremophile Adaptation"],
  ["Ecohydrology", "Water-Soil-Plant Interactions"],
  ["Ecohydrology", "Hydrological Modeling"],
  ["Ecohydrology", "Catchment Hydrology"],
  ["Ecohydrology", "Wetland Ecology"],
  ["Ecohydrology", "Hydrological Extremes"],
  ["Ecohydrology", "Hydraulic Engineering"],
  ["Ecohydrology", "Soil Moisture Dynamics"],
  ["Ecohydrology", "Vadose Zone"],
  ["Ecohydrology", "Riparian Buffer"],
  ["Biogeochemistry", "Nutrient Cycling"],
  ["Biogeochemistry", "Carbon Sequestration"],
  ["Biogeochemistry", "Soil Biogeochemistry"],
  ["Biogeochemistry", "Aquatic Biogeochemistry"],
  ["Biogeochemistry", "Marine Biogeochemistry"],
  ["Biogeochemistry", "Terrestrial Biogeochemistry"],
  ["Biogeochemistry", "Isotope Biogeochemistry"],
  ["Biogeochemistry", "Elemental Cycles"],
  ["Biogeochemistry", "Biological Pump"],
  ["Biogeochemistry", "Oceanic Anoxic Events"],
  ["Quantum Computing", "Quantum Algorithms"],
  ["Quantum Computing", "Quantum Cryptography"],
  ["Quantum Computing", "Quantum Error Correction"],
  ["Quantum Computing", "Quantum Supremacy"],
  ["Quantum Computing", "Quantum Information Theory"],
  ["Quantum Computing", "Quantum Programming"],
  ["Quantum Computing", "Quantum Error Mitigation"],
  ["Quantum Computing", "Quantum Networking"],
  ["Quantum Computing", "Quantum Communication"],
  ["Quantum Computing", "Quantum Metrology"],
  ["Quantum Computing", "Quantum Sensing"],
  ["Microbiology", "Microbial Ecology"],
  ["Microbiology", "Pathogenic Microbes"],
  ["Microbiology", "Industrial Microbiology"],
  ["Microbiology", "Microbial Genetics"],
  ["Microbiology", "Microbial Biotechnology"],
  ["Microbiology", "Microbial Pathogenesis"],
  ["Microbiology", "Environmental Microbiology"],
  ["Microbiology", "Medical Microbiology"],
  ["Microbiology", "Quorum Sensing"],
  ["Microbiology", "Holobiont"],
  ["Microbiology", "Biofilm Formation"],
  ["Microbiology", "Horizontal Gene Transfer"],
  ["Microbiology", "Quorum Quenching"],
  ["Microbiology", "Xenomycology"],
  ["Theoretical Physics", "String Theory"],
  ["Theoretical Physics", "M-Theory"],
  ["Theoretical Physics", "Quantum Field Theory"],
  ["Theoretical Physics", "Supersymmetry"],
  ["Theoretical Physics", "Gauge Theory"],
  ["Theoretical Physics", "Quantum Gravity"],
  ["Theoretical Physics", "Cosmological Constant Problem"],
  ["Theoretical Physics", "Holographic Principle"],
  ["Theoretical Physics", "Quantum Thermodynamics"],
  ["Sustainable Development", "Renewable Energy"],
  ["Sustainable Development", "Circular Economy"],
  ["Sustainable Development", "Green Building"],
  ["Sustainable Development", "Environmental Justice"],
  ["Sustainable Development", "Sustainable Agriculture"],
  ["Sustainable Development", "Renewable Resources"],
  ["Sustainable Development", "Green Economy"],
  ["Sustainable Development", "Sustainable Tourism"],
  ["Sustainable Development", "Cradle-to-Cradle Design"],
  ["Biotechnology", "Genetically Modified Organisms"],
  ["Biotechnology", "Biopharmaceuticals"],
  ["Biotechnology", "Tissue Engineering"],
  ["Biotechnology", "Biofuels"],
  ["Biotechnology", "CRISPR Technology"],
  ["Biotechnology", "Stem Cell Research"],
  ["Biotechnology", "Bioprocess Engineering"],
  ["Biotechnology", "Synthetic Genomics"],
  ["Biotechnology", "Optogenetics"],
  ["Philosophy of Mind", "Dualism"],
  ["Philosophy of Mind", "Functionalism"],
  ["Philosophy of Mind", "Qualia"],
  ["Philosophy of Mind", "Consciousness"],
  ["Philosophy of Mind", "Mind-Body Problem"],
  ["Philosophy of Mind", "Epiphenomenalism"],
  ["Philosophy of Mind", "Mental Causation"],
  ["Philosophy of Mind", "Panpsychism"],
  ["Philosophy of Mind", "Hard Problem of Consciousness"],
  ["Philosophy of Mind", "Chinese Room Argument"],
  ["Comparative Literature", "Transnational Literature"],
  ["Comparative Literature", "Literary Theory"],
  ["Comparative Literature", "World Literature"],
  ["Comparative Literature", "Literary Translation"],
  ["Comparative Literature", "Literary Canon"],
  ["Comparative Literature", "Postcolonial Literature"],
  ["Comparative Literature", "Comparative Criticism"],
  ["Comparative Literature", "Genre Studies"],
  ["Comparative Literature", "Intertextuality"],
  ["Comparative Literature", "Ekphrasis"],
  ["Cultural Studies", "Cultural Hegemony"],
  ["Cultural Studies", "Media Representation"],
  ["Cultural Studies", "Popular Culture"],
  ["Cultural Studies", "Identity Politics"],
  ["Cultural Studies", "Digital Culture"],
  ["Cultural Studies", "Visual Culture"],
  ["Cultural Studies", "Subcultures"],
  ["Cultural Studies", "Cultural Citizenship"],
  ["Cultural Studies", "Cultural Appropriation"],
  ["Political Philosophy", "Social Contract"],
  ["Political Philosophy", "Justice Theory"],
  ["Political Philosophy", "Liberalism"],
  ["Political Philosophy", "Anarchism"],
  ["Political Philosophy", "Libertarianism"],
  ["Political Philosophy", "Communitarianism"],
  ["Political Philosophy", "Social Justice"],
  ["Political Philosophy", "Deliberative Democracy"],
  ["Political Philosophy", "Social Contract Theory"],
  ["Political Philosophy", "Veil of Ignorance"],
  ["Media Studies", "Media Effects"],
  ["Media Studies", "Media Convergence"],
  ["Media Studies", "Digital Media"],
  ["Media Studies", "Media Literacy"],
  ["Media Studies", "Media Globalization"],
  ["Media Studies", "New Media"],
  ["Media Studies", "Media Production"],
  ["Media Studies", "Media Consumption"],
  ["Media Studies", "Filter Bubble"],
  ["Historical Linguistics", "Language Change"],
  ["Historical Linguistics", "Comparative Method"],
  ["Historical Linguistics", "Proto-Languages"],
  ["Historical Linguistics", "Linguistic Reconstruction"],
  ["Historical Linguistics", "Linguistic Typology"],
  ["Historical Linguistics", "Language Families"],
  ["Historical Linguistics", "Etymology"],
  ["Historical Linguistics", "Grimm's Law"],
  ["Semiotics", "Sign Systems"],
  ["Semiotics", "Symbolic Interactionism"],
  ["Semiotics", "Structuralism"],
  ["Semiotics", "Peircean Semiotics"],
  ["Semiotics", "Cultural Semiotics"],
  ["Semiotics", "Semiotic Square"],
  ["Semiotics", "Floating Signifier"],
  ["International Relations", "Realism Theory"],
  ["International Relations", "Constructivism"],
  ["International Relations", "Global Governance"],
  ["International Relations", "International Security"],
  ["International Relations", "Soft Power"],
  ["International Relations", "Balance of Power"],
  ["Economic History", "Industrial Revolution"],
  ["Economic History", "Economic Cycles"],
  ["Economic History", "Trade History"],
  ["Economic History", "Financial Crises"],
  ["Economic History", "Enclosure Movement"],
  ["Behavioral Economics", "Prospect Theory"],
  ["Behavioral Economics", "Nudge Theory"],
  ["Behavioral Economics", "Loss Aversion"],
  ["Behavioral Economics", "Bounded Rationality"],
  ["Behavioral Economics", "Hyperbolic Discounting"],
  ["Development Economics", "Microfinance"],
  ["Development Economics", "Poverty Traps"],
  ["Development Economics", "Human Capital"],
  ["Development Economics", "Sustainable Development Goals"],
  ["Development Economics", "Dependency Theory"],
  ["Development Economics", "Capability Approach"],
  ["Labor Economics", "Labor Market Dynamics"],
  ["Labor Economics", "Wage Determination"],
  ["Labor Economics", "Unemployment"],
  ["Labor Economics", "Labor Mobility"],
  ["Labor Economics", "Monopsony"],
  ["Labor Economics", "Efficiency Wage Theory"],
  ["Labor Economics", "Insider-Outsider Theory"],
  ["Public Policy", "Policy Analysis"],
  ["Public Policy", "Regulatory Policy"],
  ["Public Policy", "Social Policy"],
  ["Public Policy", "Health Policy"],
  ["Public Policy", "Policy Window"],
  ["Public Policy", "Policy Feedback"],
  ["Human Rights", "Universal Declaration of Human Rights"],
  ["Human Rights", "Humanitarian Intervention"],
  ["Human Rights", "Transitional Justice"],
  ["Human Rights", "Indigenous Rights"],
  ["Human Rights", "Universal Jurisdiction"],
  ["Human Rights", "Responsibility to Protect"],
  ["Gender Studies", "Gender Performativity"],
  ["Gender Studies", "Intersectionality"],
  ["Gender Studies", "Feminist Theory"],
  ["Gender Studies", "Masculinity Studies"],
  ["Urban Sociology", "Gentrification"],
  ["Urban Sociology", "Urban Poverty"],
  ["Urban Sociology", "Urban Social Movements"],
  ["Urban Sociology", "Urban Subcultures"],
  ["Urban Sociology", "Walkability"],
  ["Criminology", "Theories of Crime"],
  ["Criminology", "White-Collar Crime"],
  ["Criminology", "Juvenile Delinquency"],
  ["Criminology", "Crime Prevention"],
  ["Criminology", "Broken Windows Theory"],
  ["Criminology", "Differential Association Theory"],
  ["Social Movements", "Collective Behavior"],
  ["Social Movements", "Resource Mobilization"],
  ["Social Movements", "Social Movement Theories"],
  ["Social Movements", "Grassroots Activism"],
  ["Social Movements", "Repertoires of Contention"],
  ["Social Movements", "Framing Processes"],
  ["Social Stratification", "Social Class"],
  ["Social Stratification", "Social Mobility"],
  ["Social Stratification", "Income Inequality"],
  ["Social Stratification", "Status Groups"],
  ["Social Stratification", "Cultural Capital"],
  ["Social Stratification", "Social Capital"],
  ["Visual Arts", "Art Criticism"],
  ["Visual Arts", "Contemporary Art"],
  ["Visual Arts", "Art Techniques"],
  ["Visual Arts", "Art Therapy"],
  ["Visual Arts", "Anamorphosis"],
  ["Visual Arts", "Iconography"],
  ["Visual Arts", "Spectral Music"],
  ["Visual Arts", "Trompe-l'œil"],
  ["Visual Arts", "Chiaroscuro"],
  ["Art History", "Renaissance Art"],
  ["Art History", "Impressionism"],
  ["Art History", "Abstract Expressionism"],
  ["Art History", "Art Nouveau"],
  ["Art History", "Provenance"],
  ["Musicology", "Ethnomusicology"],
  ["Musicology", "Music Theory"],
  ["Musicology", "Music Cognition"],
  ["Musicology", "Music History"],
  ["Musicology", "Serialism"],
  ["Musicology", "Microtonality"],
  ["Film Studies", "Film Theory"],
  ["Film Studies", "Cinematic Techniques"],
  ["Film Studies", "Genre Studies"],
  ["Film Studies", "Film Criticism"],
  ["Film Studies", "Mise-en-scène"],
  ["Film Studies", "Diegetic Sound"],
  ["Film Studies", "Montage"],
  ["Theatre Studies", "Performance Theory"],
  ["Theatre Studies", "Dramatic Literature"],
  ["Theatre Studies", "Stage Design"],
  ["Theatre Studies", "Acting Techniques"],
  ["Theatre Studies", "Brechtian Alienation"],
  ["Theatre Studies", "Fourth Wall"],
  ["Theatre Studies", "Metatheatre"],
  ["Digital Humanities", "Digital Archives"],
  ["Digital Humanities", "Text Mining"],
  ["Digital Humanities", "Digital Pedagogy"],
  ["Digital Humanities", "Digital Scholarship"],
  ["Digital Humanities", "Distant Reading"],
  ["Digital Humanities", "Topic Modeling"],
  ["Religious Studies", "Religious Rituals"],
  ["Religious Studies", "Comparative Religion"],
  ["Religious Studies", "Secularism"],
  ["Religious Studies", "Religious Pluralism"],
  ["Religious Studies", "Syncretism"],
  ["Religious Studies", "Soteriology"],
  ["Comparative Religion", "Myth and Mythology"],
  ["Comparative Religion", "Sacred Texts"],
  ["Comparative Religion", "Religious Syncretism"],
  ["Comparative Religion", "Interfaith Dialogue"],
  ["Comparative Religion", "Theodicy"],
  ["Comparative Religion", "Eschatology"],
  ["Folklore Studies", "Oral Traditions"],
  ["Folklore Studies", "Folktales"],
  ["Folklore Studies", "Folk Beliefs"],
  ["Folklore Studies", "Urban Legends"],
  ["Folklore Studies", "Liminality"],
  ["Folklore Studies", "Rite of Passage"],
  ["Mythology", "Creation Myths"],
  ["Mythology", "Hero's Journey"],
  ["Mythology", "Mythical Creatures"],
  ["Mythology", "Myth Interpretation"],
  ["Mythology", "Monomyth"],
  ["Mythology", "Trickster Archetype"],
  ["Classical Studies", "Greek Tragedy"],
  ["Classical Studies", "Roman Law"],
  ["Classical Studies", "Classical Mythology"],
  ["Classical Studies", "Classical Philosophy"],
  ["Classical Studies", "Attic Orators"],
  ["Classical Studies", "Stoicism"],
  ["Postcolonial Studies", "Colonial Discourse"],
  ["Postcolonial Studies", "Subaltern Studies"],
  ["Postcolonial Studies", "Postcolonial Identity"],
  ["Postcolonial Studies", "Hybridity"],
  ["Postcolonial Studies", "Orientalism"],
  ["Peace and Conflict Studies", "Conflict Resolution"],
  ["Peace and Conflict Studies", "Peacebuilding"],
  ["Peace and Conflict Studies", "Nonviolent Resistance"],
  ["Peace and Conflict Studies", "Peace Education"],
  ["Peace and Conflict Studies", "Negative Peace"],
  ["Peace and Conflict Studies", "Conflict Transformation"],
  ["Peace and Conflict Studies", "Positive Peace"],
  ["Legal Studies", "Comparative Law"],
  ["Legal Studies", "Legal Theory"],
  ["Legal Studies", "Human Rights Law"],
  ["Legal Studies", "Constitutional Law"],
  ["Legal Studies", "Legal Pluralism"],
  ["Legal Studies", "Legal Hermeneutics"],
  ["Legal Studies", "Legal Positivism"],
  ["Political Economy", "Political Capitalism"],
  ["Political Economy", "Globalization"],
  ["Political Economy", "Developmental State"],
  ["Political Economy", "Welfare State"],
  ["Political Economy", "Rent-seeking"],
  ["Political Economy", "Oligarchy"],
  ["Political Economy", "Regulatory Capture"],
  ["Constitutional Law", "Judicial Review"],
  ["Constitutional Law", "Separation of Powers"],
  ["Constitutional Law", "Federalism"],
  ["Constitutional Law", "Constitutional Amendments"],
  ["Constitutional Law", "Checks and Balances"],
  ["Environmental Law", "Environmental Impact Assessment"],
  ["Environmental Law", "Sustainable Development Law"],
  ["Environmental Law", "Climate Change Law"],
  ["Environmental Law", "Biodiversity Law"],
  ["Environmental Law", "Precautionary Principle"],
  ["Environmental Law", "Polluter Pays Principle"],
  ["Journalism", "Investigative Journalism"],
  ["Journalism", "Data Journalism"],
  ["Journalism", "Media Ethics"],
  ["Journalism", "Journalistic Objectivity"],
  ["Journalism", "Agenda-Setting Theory"],
  ["Journalism", "Churnalism"],
  ["Journalism", "Gatekeeping"],
  ["Public Relations", "Crisis Management"],
  ["Public Relations", "Reputation Management"],
  ["Public Relations", "Media Relations"],
  ["Public Relations", "Corporate Communication"],
  ["Public Relations", "Astroturfing"],
  ["Public Relations", "Crisis Communication"],
  ["Advertising", "Brand Positioning"],
  ["Advertising", "Consumer Behavior"],
  ["Advertising", "Advertising Campaigns"],
  ["Advertising", "Digital Advertising"],
  ["Advertising", "Neuromarketing"],
  ["Advertising", "Subliminal Messaging"],
  ["Advertising", "Viral Marketing"],
  ["Organizational Communication", "Corporate Culture"],
  ["Organizational Communication", "Leadership Communication"],
  ["Organizational Communication", "Internal Communication"],
  ["Organizational Communication", "Organizational Change"],
  ["Organizational Communication", "Organizational Storytelling"],
  ["Interpersonal Communication", "Nonverbal Communication"],
  ["Interpersonal Communication", "Conflict Resolution"],
  ["Interpersonal Communication", "Interpersonal Attraction"],
  ["Interpersonal Communication", "Listening Skills"],
  ["Interpersonal Communication", "Proxemics"],
  ["Interpersonal Communication", "Kinesics"],
  ["Communication Ethics", "Free Speech"],
  ["Communication Ethics", "Privacy Issues"],
  ["Communication Ethics", "Media Accountability"],
  ["Communication Ethics", "Digital Ethics"],
  ["Communication Ethics", "Virtue Ethics"],
  ["Communication Ethics", "Deontological Ethics"],
  ["Rhetoric", "Aristotelian Rhetoric"],
  ["Rhetoric", "Rhetorical Criticism"],
  ["Rhetoric", "Rhetorical Devices"],
  ["Rhetoric", "Political Rhetoric"],
  ["Rhetoric", "Enthymeme"],
  ["Rhetoric", "Pathos"],
  ["Discourse Analysis", "Critical Discourse Analysis"],
  ["Discourse Analysis", "Conversation Analysis"],
  ["Discourse Analysis", "Narrative Analysis"],
  ["Discourse Analysis", "Discourse and Power"],
  ["Discourse Analysis", "Intertextuality"],
  ["Pragmatics", "Speech Acts"],
  ["Pragmatics", "Politeness Theory"],
  ["Pragmatics", "Deixis"],
  ["Pragmatics", "Implicature"],
  ["Philosophy of Language", "Language and Thought"],
  ["Philosophy of Language", "Meaning and Reference"],
  ["Philosophy of Language", "Speech Act Theory"],
  ["Philosophy of Language", "Linguistic Relativity"],
  ["Philosophy of Language", "Sapir-Whorf Hypothesis"],
  ["Philosophy of Language", "Linguistic Determinism"],
  ["Phenomenology", "Intentionality"],
  ["Phenomenology", "Lifeworld"],
  ["Phenomenology", "Embodiment"],
  ["Phenomenology", "Inter-subjectivity"],
  ["Phenomenology", "Epoché"],
  ["Existentialism", "Absurdism"],
  ["Existentialism", "Authenticity"],
  ["Existentialism", "Freedom and Responsibility"],
  ["Existentialism", "Existential Angst"],
  ["Existentialism", "Bad Faith"],
  ["Ethics", "Virtue Ethics"],
  ["Ethics", "Deontological Ethics"],
  ["Ethics", "Utilitarianism"],
  ["Ethics", "Ethical Relativism"],
  ["Ethics", "Moral Particularism"],
  ["Ethics", "Moral Relativism"],
  ["Aesthetics", "The Sublime"],
  ["Aesthetics", "Art and Morality"],
  ["Aesthetics", "Aesthetic Experience"],
  ["Aesthetics", "Philosophy of Art"],
  ["Aesthetics", "Kitsch"],
  ["Epistemology", "Skepticism"],
  ["Epistemology", "Foundationalism"],
  ["Epistemology", "Coherentism"],
  ["Epistemology", "Social Epistemology"],
  ["Epistemology", "Gettier Problem"],
  ["Epistemology", "Cogito Ergo Sum"]
];

export default conceptFieldPairs;